name: OWASP ZAP Full Scan

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  zap-full-scan:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'https://localhost:3000'
          cmd_options: '-config api.disablekey=true -config scanner.attackOnStart=true'
          artifact_name: 'zap_scan'

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: ZAP_Scan_Report
          path: zap_scan
