name: ZAP Full Scan

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  zap-full-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'https://juice-shop.herokuapp.com'
          format: 'html'
          report: 'zap_report.html'
          cmd_options: '-config api.disablekey=true -config scanner.attackOnStart=true'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: ZAP_Scan_Report
          path: zap_report.html
