name: "Local SQL Injection Testing"


on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:


jobs:
  zap-sql-injection-scan:
    runs-on: self-hosted
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v3

      - name: "Set up OWASP ZAP in Docker"
        run: |
          if [ ! "$(docker ps -q -f name=zap)" ]; then
            if [ "$(docker ps -aq -f status=exited -f name=zap)" ]; then
              docker rm zap
            fi
            docker run -d -u zap -p 8080:8080 --name zap ghcr.io/zaproxy/zaproxy zap.sh -daemon -port 8080 -config api.disablekey=true
          else
            echo "ZAP container is already running."
          fi

      - name: "Run OWASP ZAP SQL Injection Test"
        run: |
          curl "http://localhost:8080/JSON/ascan/action/scan/?url=http://localhost:3000"
          echo "Waiting for scan to complete..."
          while [ "$(curl -s http://localhost:8080/JSON/ascan/view/status/?scanId=0 | jq -r '.status')" != "100" ]; do
            sleep 10
          done
          echo "Scan completed."

      - name: "Generate ZAP HTML Report"
        run: |
          curl "http://localhost:8080/OTHER/core/other/htmlreport/" -o zap_report.html

      - name: "Upload Report"
        uses: actions/upload-artifact@v3
        with:
          name: zap_report
          path: zap_report.html
