name: "Automated Security Testing for SQL Injection"

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  sql_injection_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker environment
        run: |
          # Pull and start OWASP ZAP targeting localhost
          docker pull ghcr.io/zaproxy/zaproxy
          docker run -d -u zap -p 8080:8080 --name zap ghcr.io/zaproxy/zaproxy zap.sh -daemon -port 8080 -config api.disablekey=true

      - name: Run OWASP ZAP SQL Injection Test
        run: |
          # Run OWASP ZAP scan targeting the Juice Shop instance on localhost:3000
          docker exec zap zap-cli quick-scan --self-contained --start-options '-config api.disablekey=true' http://localhost:3000
        continue-on-error: true

      - name: Process ZAP Results
        run: |
          docker exec zap zap-cli report -o zap_report.html -f html
          docker cp zap:/zap/zap_report.html .
        continue-on-error: true

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: zap_report
          path: zap_report.html
