name: Automated security testing for SQL injection

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
jobs:
  zap-sql-injection-scan:
    runs-on: self-hosted

    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v3

      - name: "Set up OWASP ZAP in Docker"
        run: |
          if [ ! "$(docker ps -q -f name=zap)" ]; then
            if [ "$(docker ps -aq -f status=exited -f name=zap)" ]; then
              docker rm zap
            fi
            docker run -d -u zap -p 8080:8080 --name zap ghcr.io/zaproxy/zaproxy zap.sh -daemon -port 8080 -config api.disablekey=true
          else
            echo "ZAP container is already running."
          fi

      - name: "Run OWASP ZAP SQL Injection Test"
        run: |
          docker exec zap zap-cli quick-scan --self-contained --start-options '-config api.disablekey=true' http://localhost:3000
        continue-on-error: true

      - name: "Process ZAP Results"
        run: |
          docker exec zap zap-cli report -o zap_report.html -f html
          docker cp zap:/zap/zap_report.html .
        continue-on-error: true

      - name: "Upload Report"
        uses: actions/upload-artifact@v3
        with:
          name: zap_report
          path: zap_report.html
