

name: "OWASP Dependency-Check"

on:
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    name: Run OWASP Dependency-Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11' 

    - name: Run OWASP Dependency-Check
      uses: jeremylong/dependency-check-action@v3
      with:
        project: "auto testing"               
        scan: "./"                         
        format: "ALL"                       
        outputDirectory: "./dependency-check-report" 
       
        updateOnly: true                  
        failBuildOnCVSS: 7                

    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: ./dependency-check-report

    - name: Cleanup Docker Containers
      run: |
        docker container prune -f       # Remove all stopped containers
        docker image prune -f            # Remove dangling images
