name: Detect Secrets

on:
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install detect-secrets

    - name: Scan for secrets
      run: |
        detect-secrets scan --all-files | tee scan-results.txt
        if grep -q "Potential Secrets" scan-results.txt; then
          exit 1
        fi
