# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Devskim Automated Security Check
on: [push, pull_request]

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
    - run: echo "Build application"
    
  scan:
    name: Devskim scans
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - run: npm install ci
    - run: npm ci
    - run: .comp4035/tools/dependency-check/bin/dependency-check.sh -s . -o .comp4035/output --disableAssembly

    - uses: microsoft/devskim-action@v1
      with:
        output-filename: devskim-results.sarif
        output-directory: .comp4035/output

    - uses: actions/upload-artifact@v2
      with: 
        name: scan-results
        path: .comp4035/output
        
  deploy:
    name: Deploy
    needs: scan
    runs-on: ubuntu-latest
    steps:
    - run: echo "Deploy application"
