name: DevSkim Security Scan

on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  devskim_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #v2: v2.3.4 available

    - name: Install .NET SDK
      run: sudo apt-get install -y dotnet-sdk-5.0

    - name: Install DevSkim CLI
      run: dotnet tool install --global Microsoft.CST.DevSkim.CLI

    - name: Run DevSkim
      run: devskim analyze ./
  