# Friendly name for the workflow in GitHub
name: Continuous Integration (CI) Security Pipeline
# Run the workflow each time code is pushed, or when a pull-request is created
on: [push, pull_request]

jobs:
  # Build the app
  build:
    # Configure the job 
    name: Build
    runs-on: ubuntu-latest
    # Steps to run
    steps:
    - run: echo "Build the app..."
    - run: echo "Not implemented to save time when running the workflow"

  # Run security scans
  scan:
    # Configure the job 
    name: Run security scans
    needs: build
    runs-on: ubuntu-latest

    # Steps to run
    steps:

    # Set up prerequisites for static code analysis
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1

    # # Install node packages
    # - run: npm ci
    
    # Run static code analysis checks
    # DevSkim https://github.com/microsoft/DevSkim-Action 
    - uses: microsoft/devskim-action@v1
      with:
        directory-to-scan: /
        should-scan-archives: false
        output-filename: devskim-results.sarif
        output-directory: .github/workflows/outputs

    # Publish the scan results as an artifact
    - uses: actions/upload-artifact@v2
      with: 
        name: scan-results
        path: .github/workflows/outputs

  # Deploy the app
  deploy:
    # Configure the job 
    name: Deploy
    needs: scan
    runs-on: ubuntu-latest

    # Steps to run
    steps:
    - run: echo "Deploy the app..."
    - run: echo "Not implemented to save time when running the workflow"
