# Friendly name for the workflow in GitHub
name: Static Testing
# Run the workflow each time code is pushed, or when a pull-request is created
on: [push, pull_request]

jobs:
  static:
    # Configure the job
    name: static testing
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run DevSkim scanner
      uses: microsoft/DevSkim-Action@v1

    - name: Upload results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: devskim-results.sarif

  depchecktest:
    # Configure the job
    name: depecheck_test
    runs-on: ubuntu-latest
    needs: static

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project
        run: npm install --package-lock
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports