# Friendly name for the workflow in GitHub
name: Static Testing
# Run the workflow each time code is pushed, or when a pull-request is created
on: [push, pull_request]

jobs:
  static:
    # Configure the job
    name: static testing
    runs-on: ubuntu-latest
    steps:
     # Set up prerequisites for tests
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1

    # Install node packages
    - run: npm install --ignore-scripts --legacy-peer-deps

    # DevSkim
    # - Some CI support inbuilt tasks and scans, for  ease of use
    # - We could install and run DevSkim directly, but we can do it more easily using the DevSkim action
    # - See docs at: https://github.com/microsoft/DevSkim-Action git
    - uses: microsoft/devskim-action@v1
      with:
        directory-to-scan: /
        should-scan-archives: false
        output-filename: devskim-results.sarif
        output-directory: output/

    # Publish the scan results as an artifact
    - uses: actions/upload-artifact@v2
      with: 
        name: scan-results
        path: output/

  depchecktest:
    # Configure the job
    name: depecheck_test
    runs-on: ubuntu-latest
    needs: static

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project with Maven
        run: mvn clean install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

  # Build the app
  build:
    # Configure the job 
    name: Build
    needs: depchecktest
    runs-on: ubuntu-latest
    # Steps to run
    steps:
    - run: echo "Build the app..."
    - run: echo "Not implemented to save time when running the workflow"
  
  # Run security scans
  tests:
    # Configure the job 
    name: Run security scans
    needs: build
    runs-on: ubuntu-latest

    steps:
    - run: echo "Testing the app..."