name: "OWASP ZAP Baseline Scan"

on: 
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan unisa guardian shop
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:3000/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j -autorun zap.yaml'
