name: "OWASP ZAP Baseline Scan"

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan unisa guardian shop
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:3000/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j -cmd -autorun zap.yaml'
