name: "On-pull ZAP Baseline Scan"

on:
  push:
  pull_request:
    branches:
      - main
      - develop



jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop preview instance on Heroku
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2 #v2: v2.3.4 available
        with:
          ref: main
      - name: Building Docker Node-Goat Image
        run: docker-compose build
      - name: Launching the app
        run: docker-compose up --detach

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Target URL
          target: "http://localhost:3000"
          issue_title: Security Tests
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j -failOnAlert -config failRule=HIGH'
