name: "ZAP Baseline Scan"
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  schedule:
    - cron: '20 9 * * 5'

    
jobs:
  
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop instance
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'