name: "ZAP Full Scan for XSS"

on: [pull_request]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ZAP Active XSS Scan Backend
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: http://localhost:3000
          rules_file_name: xss_rules.tsv
          fail_action: false
          token: $
          artifact_name: backend-zap
      - name: ZAP Active XSS Scan Backend
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: http://localhost:4200
          rules_file_name: xss_rules.tsv
          fail_action: false
          token: $
          artifact_name: frontend-zap
      
