name: "ZAP Baseline Scan"

on:
  push

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop preview instance on Heroku
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: sudo apt-get update && sudo apt-get install -y nginx && sudo systemctl start nginx
      
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost'
          cmd_options: '-a -j'
